// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __myproject_w6_V_H__
#define __myproject_w6_V_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct myproject_w6_V_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 12;
  static const unsigned AddressRange = 64;
  static const unsigned AddressWidth = 6;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(myproject_w6_V_ram) {
        ram[0] = "0b000011101010";
        ram[1] = "0b000000110010";
        ram[2] = "0b111010110011";
        ram[3] = "0b000000010011";
        ram[4] = "0b111000101001";
        ram[5] = "0b000101010000";
        ram[6] = "0b000001010111";
        ram[7] = "0b111001111011";
        ram[8] = "0b111101001101";
        ram[9] = "0b110100001111";
        ram[10] = "0b110101110000";
        ram[11] = "0b000011110001";
        ram[12] = "0b111000000101";
        ram[13] = "0b000000001000";
        ram[14] = "0b100001011101";
        ram[15] = "0b110110110000";
        ram[16] = "0b000001110111";
        ram[17] = "0b000011111110";
        ram[18] = "0b000011010101";
        ram[19] = "0b111000110100";
        ram[20] = "0b001111000101";
        ram[21] = "0b111001111111";
        ram[22] = "0b110101110110";
        ram[23] = "0b111001100010";
        ram[24] = "0b000000111111";
        ram[25] = "0b111110001011";
        ram[26] = "0b111101110101";
        ram[27] = "0b111011110101";
        ram[28] = "0b110011101101";
        ram[29] = "0b000000000010";
        ram[30] = "0b111111110101";
        ram[31] = "0b000001101000";
        ram[32] = "0b000101010010";
        ram[33] = "0b000110101001";
        ram[34] = "0b000001000100";
        ram[35] = "0b111101100100";
        ram[36] = "0b000010110001";
        ram[37] = "0b111011100000";
        ram[38] = "0b110111100100";
        ram[39] = "0b111000011110";
        ram[40] = "0b111100010110";
        ram[41] = "0b110110010110";
        ram[42] = "0b111110100011";
        ram[43] = "0b110110100101";
        ram[44] = "0b000001001101";
        ram[45] = "0b111001010011";
        ram[46] = "0b111010010111";
        ram[47] = "0b000000110010";
        ram[48] = "0b000000001000";
        ram[49] = "0b000001110010";
        ram[50] = "0b110001010111";
        ram[51] = "0b110110110010";
        ram[52] = "0b111000000110";
        ram[53] = "0b000010100111";
        ram[54] = "0b000000111001";
        ram[55] = "0b111111110111";
        ram[56] = "0b000000000101";
        ram[57] = "0b001101010100";
        ram[58] = "0b000100010011";
        ram[59] = "0b111101001001";
        ram[60] = "0b000010011011";
        ram[61] = "0b111010000110";
        ram[62] = "0b000000100101";
        ram[63] = "0b000100000000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(myproject_w6_V) {


static const unsigned DataWidth = 12;
static const unsigned AddressRange = 64;
static const unsigned AddressWidth = 6;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


myproject_w6_V_ram* meminst;


SC_CTOR(myproject_w6_V) {
meminst = new myproject_w6_V_ram("myproject_w6_V_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~myproject_w6_V() {
    delete meminst;
}


};//endmodule
#endif
