-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity myproject_w6_V_rom is 
    generic(
             DWIDTH     : integer := 12; 
             AWIDTH     : integer := 6; 
             MEM_SIZE    : integer := 64
    ); 
    port (
          addr0      : in std_logic_vector(AWIDTH-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(DWIDTH-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of myproject_w6_V_rom is 

signal addr0_tmp : std_logic_vector(AWIDTH-1 downto 0); 
type mem_array is array (0 to MEM_SIZE-1) of std_logic_vector (DWIDTH-1 downto 0); 
signal mem : mem_array := (
    0 => "000011101010", 1 => "000000110010", 2 => "111010110011", 
    3 => "000000010011", 4 => "111000101001", 5 => "000101010000", 
    6 => "000001010111", 7 => "111001111011", 8 => "111101001101", 
    9 => "110100001111", 10 => "110101110000", 11 => "000011110001", 
    12 => "111000000101", 13 => "000000001000", 14 => "100001011101", 
    15 => "110110110000", 16 => "000001110111", 17 => "000011111110", 
    18 => "000011010101", 19 => "111000110100", 20 => "001111000101", 
    21 => "111001111111", 22 => "110101110110", 23 => "111001100010", 
    24 => "000000111111", 25 => "111110001011", 26 => "111101110101", 
    27 => "111011110101", 28 => "110011101101", 29 => "000000000010", 
    30 => "111111110101", 31 => "000001101000", 32 => "000101010010", 
    33 => "000110101001", 34 => "000001000100", 35 => "111101100100", 
    36 => "000010110001", 37 => "111011100000", 38 => "110111100100", 
    39 => "111000011110", 40 => "111100010110", 41 => "110110010110", 
    42 => "111110100011", 43 => "110110100101", 44 => "000001001101", 
    45 => "111001010011", 46 => "111010010111", 47 => "000000110010", 
    48 => "000000001000", 49 => "000001110010", 50 => "110001010111", 
    51 => "110110110010", 52 => "111000000110", 53 => "000010100111", 
    54 => "000000111001", 55 => "111111110111", 56 => "000000000101", 
    57 => "001101010100", 58 => "000100010011", 59 => "111101001001", 
    60 => "000010011011", 61 => "111010000110", 62 => "000000100101", 
    63 => "000100000000" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity myproject_w6_V is
    generic (
        DataWidth : INTEGER := 12;
        AddressRange : INTEGER := 64;
        AddressWidth : INTEGER := 6);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of myproject_w6_V is
    component myproject_w6_V_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    myproject_w6_V_rom_U :  component myproject_w6_V_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


