// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "k2c_matmul.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic k2c_matmul::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic k2c_matmul::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<13> k2c_matmul::ap_ST_fsm_state1 = "1";
const sc_lv<13> k2c_matmul::ap_ST_fsm_state2 = "10";
const sc_lv<13> k2c_matmul::ap_ST_fsm_state3 = "100";
const sc_lv<13> k2c_matmul::ap_ST_fsm_state4 = "1000";
const sc_lv<13> k2c_matmul::ap_ST_fsm_state5 = "10000";
const sc_lv<13> k2c_matmul::ap_ST_fsm_state6 = "100000";
const sc_lv<13> k2c_matmul::ap_ST_fsm_pp0_stage0 = "1000000";
const sc_lv<13> k2c_matmul::ap_ST_fsm_pp0_stage1 = "10000000";
const sc_lv<13> k2c_matmul::ap_ST_fsm_pp0_stage2 = "100000000";
const sc_lv<13> k2c_matmul::ap_ST_fsm_pp0_stage3 = "1000000000";
const sc_lv<13> k2c_matmul::ap_ST_fsm_pp0_stage4 = "10000000000";
const sc_lv<13> k2c_matmul::ap_ST_fsm_pp0_stage5 = "100000000000";
const sc_lv<13> k2c_matmul::ap_ST_fsm_state19 = "1000000000000";
const bool k2c_matmul::ap_const_boolean_1 = true;
const sc_lv<32> k2c_matmul::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> k2c_matmul::ap_const_lv32_1 = "1";
const sc_lv<32> k2c_matmul::ap_const_lv32_2 = "10";
const sc_lv<1> k2c_matmul::ap_const_lv1_1 = "1";
const sc_lv<32> k2c_matmul::ap_const_lv32_3 = "11";
const sc_lv<32> k2c_matmul::ap_const_lv32_4 = "100";
const sc_lv<32> k2c_matmul::ap_const_lv32_5 = "101";
const sc_lv<32> k2c_matmul::ap_const_lv32_6 = "110";
const bool k2c_matmul::ap_const_boolean_0 = false;
const sc_lv<1> k2c_matmul::ap_const_lv1_0 = "0";
const sc_lv<32> k2c_matmul::ap_const_lv32_7 = "111";
const sc_lv<32> k2c_matmul::ap_const_lv32_8 = "1000";
const sc_lv<32> k2c_matmul::ap_const_lv32_9 = "1001";
const sc_lv<32> k2c_matmul::ap_const_lv32_A = "1010";
const sc_lv<32> k2c_matmul::ap_const_lv32_B = "1011";
const sc_lv<15> k2c_matmul::ap_const_lv15_0 = "000000000000000";
const sc_lv<192> k2c_matmul::ap_const_lv192_lc_1 = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> k2c_matmul::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<128> k2c_matmul::ap_const_lv128_lc_1 = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<15> k2c_matmul::ap_const_lv15_1 = "1";
const sc_lv<64> k2c_matmul::ap_const_lv64_1 = "1";
const sc_lv<128> k2c_matmul::ap_const_lv128_lc_2 = "1";
const sc_lv<192> k2c_matmul::ap_const_lv192_lc_2 = "1";
const sc_lv<16> k2c_matmul::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> k2c_matmul::ap_const_lv32_C = "1100";

k2c_matmul::k2c_matmul(sc_module_name name) : sc_module(name), mVcdFile(0) {
    WebModel_fadd_32ncud_U6 = new WebModel_fadd_32ncud<1,5,32,32,32>("WebModel_fadd_32ncud_U6");
    WebModel_fadd_32ncud_U6->clk(ap_clk);
    WebModel_fadd_32ncud_U6->reset(ap_rst);
    WebModel_fadd_32ncud_U6->din0(C_q0);
    WebModel_fadd_32ncud_U6->din1(tmp_3_reg_679);
    WebModel_fadd_32ncud_U6->ce(ap_var_for_const0);
    WebModel_fadd_32ncud_U6->dout(grp_fu_187_p2);
    WebModel_fmul_32ndEe_U7 = new WebModel_fmul_32ndEe<1,3,32,32,32>("WebModel_fmul_32ndEe_U7");
    WebModel_fmul_32ndEe_U7->clk(ap_clk);
    WebModel_fmul_32ndEe_U7->reset(ap_rst);
    WebModel_fmul_32ndEe_U7->din0(B_load_3_reg_649);
    WebModel_fmul_32ndEe_U7->din1(B_load_reg_654);
    WebModel_fmul_32ndEe_U7->ce(ap_var_for_const0);
    WebModel_fmul_32ndEe_U7->dout(grp_fu_193_p2);
    WebModel_mul_64s_bkb_U8 = new WebModel_mul_64s_bkb<1,2,64,64,64>("WebModel_mul_64s_bkb_U8");
    WebModel_mul_64s_bkb_U8->clk(ap_clk);
    WebModel_mul_64s_bkb_U8->reset(ap_rst);
    WebModel_mul_64s_bkb_U8->din0(outcols);
    WebModel_mul_64s_bkb_U8->din1(outrows);
    WebModel_mul_64s_bkb_U8->ce(ap_var_for_const0);
    WebModel_mul_64s_bkb_U8->dout(grp_fu_197_p2);
    WebModel_mul_64nseOg_U9 = new WebModel_mul_64nseOg<1,2,64,64,128>("WebModel_mul_64nseOg_U9");
    WebModel_mul_64nseOg_U9->clk(ap_clk);
    WebModel_mul_64nseOg_U9->reset(ap_rst);
    WebModel_mul_64nseOg_U9->din0(grp_fu_228_p0);
    WebModel_mul_64nseOg_U9->din1(grp_fu_228_p1);
    WebModel_mul_64nseOg_U9->ce(ap_var_for_const0);
    WebModel_mul_64nseOg_U9->dout(grp_fu_228_p2);
    WebModel_mul_128nfYi_U10 = new WebModel_mul_128nfYi<1,2,128,64,192>("WebModel_mul_128nfYi_U10");
    WebModel_mul_128nfYi_U10->clk(ap_clk);
    WebModel_mul_128nfYi_U10->reset(ap_rst);
    WebModel_mul_128nfYi_U10->din0(grp_fu_243_p0);
    WebModel_mul_128nfYi_U10->din1(grp_fu_243_p1);
    WebModel_mul_128nfYi_U10->ce(ap_var_for_const0);
    WebModel_mul_128nfYi_U10->dout(grp_fu_243_p2);
    WebModel_mac_mulag8j_U11 = new WebModel_mac_mulag8j<1,1,16,16,16,16>("WebModel_mac_mulag8j_U11");
    WebModel_mac_mulag8j_U11->din0(grp_fu_421_p0);
    WebModel_mac_mulag8j_U11->din1(tmp_31_reg_508);
    WebModel_mac_mulag8j_U11->din2(grp_fu_421_p2);
    WebModel_mac_mulag8j_U11->dout(grp_fu_421_p3);
    WebModel_mac_mulag8j_U12 = new WebModel_mac_mulag8j<1,1,16,16,16,16>("WebModel_mac_mulag8j_U12");
    WebModel_mac_mulag8j_U12->din0(grp_fu_428_p0);
    WebModel_mac_mulag8j_U12->din1(tmp_30_reg_524);
    WebModel_mac_mulag8j_U12->din2(tmp_32_reg_487);
    WebModel_mac_mulag8j_U12->dout(grp_fu_428_p3);
    WebModel_mac_mulahbi_U13 = new WebModel_mac_mulahbi<1,1,16,16,16,16>("WebModel_mac_mulahbi_U13");
    WebModel_mac_mulahbi_U13->din0(tmp_36_reg_618);
    WebModel_mac_mulahbi_U13->din1(tmp_31_reg_508);
    WebModel_mac_mulahbi_U13->din2(k_cast_mid2_reg_608);
    WebModel_mac_mulahbi_U13->dout(grp_fu_434_p3);
    WebModel_mul_mul_ibs_U14 = new WebModel_mul_mul_ibs<1,1,16,16,16>("WebModel_mul_mul_ibs_U14");
    WebModel_mul_mul_ibs_U14->din0(tmp_34_reg_546);
    WebModel_mul_mul_ibs_U14->din1(tmp_30_reg_524);
    WebModel_mul_mul_ibs_U14->dout(outrowidx_fu_440_p2);
    WebModel_mul_mul_ibs_U15 = new WebModel_mul_mul_ibs<1,1,16,16,16>("WebModel_mul_mul_ibs_U15");
    WebModel_mul_mul_ibs_U15->din0(tmp_36_reg_618);
    WebModel_mul_mul_ibs_U15->din1(tmp_30_reg_524);
    WebModel_mul_mul_ibs_U15->dout(outrowidx_mid1_fu_444_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( sum_cast_mid2_fu_368_p1 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_A_address1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( sum3_cast_fu_377_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_A_ce1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_C_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( C_addr_3_reg_664 );
    sensitive << ( ap_CS_fsm_pp0_stage5 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( a_cast_fu_203_p1 );
    sensitive << ( ap_block_pp0_stage5 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage5 );
    sensitive << ( ap_block_pp0_stage5_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_C_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_pp0_stage5 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage5 );
    sensitive << ( grp_fu_187_p2 );

    SC_METHOD(thread_C_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond3_fu_208_p2 );
    sensitive << ( exitcond_flatten3_reg_556_pp0_iter1_reg );
    sensitive << ( ap_CS_fsm_pp0_stage5 );
    sensitive << ( ap_block_pp0_stage5_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_a10_fu_213_p2);
    sensitive << ( a_reg_120 );

    SC_METHOD(thread_a_cast_fu_203_p1);
    sensitive << ( a_reg_120 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);

    SC_METHOD(thread_ap_block_pp0_stage3);

    SC_METHOD(thread_ap_block_pp0_stage3_11001);

    SC_METHOD(thread_ap_block_pp0_stage3_subdone);

    SC_METHOD(thread_ap_block_pp0_stage4);

    SC_METHOD(thread_ap_block_pp0_stage4_11001);

    SC_METHOD(thread_ap_block_pp0_stage4_subdone);

    SC_METHOD(thread_ap_block_pp0_stage5);

    SC_METHOD(thread_ap_block_pp0_stage5_11001);

    SC_METHOD(thread_ap_block_pp0_stage5_subdone);

    SC_METHOD(thread_ap_block_state10_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state11_pp0_stage4_iter0);

    SC_METHOD(thread_ap_block_state12_pp0_stage5_iter0);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state14_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state15_pp0_stage2_iter1);

    SC_METHOD(thread_ap_block_state16_pp0_stage3_iter1);

    SC_METHOD(thread_ap_block_state17_pp0_stage4_iter1);

    SC_METHOD(thread_ap_block_state18_pp0_stage5_iter1);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state8_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state9_pp0_stage2_iter0);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state10);
    sensitive << ( exitcond_flatten3_reg_556 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_i_phi_fu_169_p4);
    sensitive << ( i_reg_165 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_flatten3_reg_556 );
    sensitive << ( i_mid2_reg_624 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten3_phi_fu_135_p4);
    sensitive << ( indvar_flatten3_reg_131 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_flatten3_reg_556 );
    sensitive << ( indvar_flatten_next3_reg_644 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten_phi_fu_158_p4);
    sensitive << ( indvar_flatten_reg_154 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_flatten3_reg_556 );
    sensitive << ( indvar_flatten_next_reg_674 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_j_phi_fu_180_p4);
    sensitive << ( j_reg_176 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_flatten3_reg_556 );
    sensitive << ( j_1_reg_669 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_k_phi_fu_147_p4);
    sensitive << ( k_reg_143 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_flatten3_reg_556 );
    sensitive << ( k_mid2_reg_587 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_cast2_fu_225_p0);
    sensitive << ( outcols );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_cast_fu_222_p0);
    sensitive << ( outrows );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_exitcond3_fu_208_p2);
    sensitive << ( tmp_reg_474 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( a_cast_fu_203_p1 );

    SC_METHOD(thread_exitcond_flatten3_fu_265_p2);
    sensitive << ( bound5_reg_531 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten3_phi_fu_135_p4 );

    SC_METHOD(thread_exitcond_flatten_fu_270_p2);
    sensitive << ( bound_reg_502 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond_flatten3_fu_265_p2 );
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_158_p4 );

    SC_METHOD(thread_exitcond_fu_293_p1);
    sensitive << ( outcols );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_exitcond_fu_293_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond_flatten3_fu_265_p2 );
    sensitive << ( ap_phi_mux_j_phi_fu_180_p4 );
    sensitive << ( exitcond_fu_293_p1 );

    SC_METHOD(thread_exitcond_mid3_fu_298_p3);
    sensitive << ( exitcond_mid_reg_536 );
    sensitive << ( exitcond_flatten_fu_270_p2 );
    sensitive << ( exitcond_fu_293_p2 );

    SC_METHOD(thread_exitcond_mid_fu_252_p0);
    sensitive << ( outcols );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_exitcond_mid_fu_252_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond_mid_fu_252_p0 );

    SC_METHOD(thread_grp_fu_228_p0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_228_p00 );

    SC_METHOD(thread_grp_fu_228_p00);
    sensitive << ( cast2_fu_225_p0 );

    SC_METHOD(thread_grp_fu_228_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_228_p10 );

    SC_METHOD(thread_grp_fu_228_p10);
    sensitive << ( cast_fu_222_p0 );

    SC_METHOD(thread_grp_fu_243_p0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_fu_243_p00 );

    SC_METHOD(thread_grp_fu_243_p00);
    sensitive << ( bound_reg_502 );

    SC_METHOD(thread_grp_fu_243_p1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_fu_243_p10 );

    SC_METHOD(thread_grp_fu_243_p10);
    sensitive << ( innerdim );

    SC_METHOD(thread_grp_fu_421_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_phi_mux_i_phi_fu_169_p4 );

    SC_METHOD(thread_grp_fu_421_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_phi_mux_k_phi_fu_147_p4 );

    SC_METHOD(thread_grp_fu_428_p0);
    sensitive << ( tmp_33_reg_541 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond_flatten3_reg_556 );
    sensitive << ( exitcond_flatten_reg_560 );
    sensitive << ( tmp_35_reg_574 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_i_4_fu_342_p2);
    sensitive << ( i_mid_reg_568 );

    SC_METHOD(thread_i_mid2_fu_351_p3);
    sensitive << ( i_mid_reg_568 );
    sensitive << ( exitcond_mid3_reg_580 );
    sensitive << ( i_4_fu_342_p2 );

    SC_METHOD(thread_i_mid_fu_275_p3);
    sensitive << ( exitcond_flatten_fu_270_p2 );
    sensitive << ( ap_phi_mux_i_phi_fu_169_p4 );

    SC_METHOD(thread_indvar_flatten_next3_fu_382_p2);
    sensitive << ( indvar_flatten3_reg_131 );

    SC_METHOD(thread_indvar_flatten_next_fu_415_p3);
    sensitive << ( exitcond_flatten_reg_560 );
    sensitive << ( indvar_flatten_op_reg_603 );

    SC_METHOD(thread_indvar_flatten_op_fu_331_p2);
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_158_p4 );

    SC_METHOD(thread_j_1_fu_410_p2);
    sensitive << ( j_mid2_reg_592 );

    SC_METHOD(thread_j_mid2_fu_319_p3);
    sensitive << ( ap_phi_mux_j_phi_fu_180_p4 );
    sensitive << ( tmp_7_fu_313_p2 );

    SC_METHOD(thread_k_cast_mid2_fu_337_p3);
    sensitive << ( tmp_33_reg_541 );
    sensitive << ( exitcond_flatten_reg_560 );
    sensitive << ( tmp_35_reg_574 );

    SC_METHOD(thread_k_mid2_fu_305_p3);
    sensitive << ( exitcond_flatten_fu_270_p2 );
    sensitive << ( ap_phi_mux_k_phi_fu_147_p4 );
    sensitive << ( k_s_fu_283_p2 );

    SC_METHOD(thread_k_s_fu_283_p2);
    sensitive << ( ap_phi_mux_k_phi_fu_147_p4 );

    SC_METHOD(thread_outrowidx_mid2_fu_394_p3);
    sensitive << ( exitcond_mid3_reg_580 );
    sensitive << ( outrowidx_mid1_reg_659 );
    sensitive << ( outrowidx_mid_fu_388_p3 );

    SC_METHOD(thread_outrowidx_mid_fu_388_p3);
    sensitive << ( exitcond_flatten_reg_560 );
    sensitive << ( outrowidx_reg_639 );

    SC_METHOD(thread_sum2_cast_fu_405_p1);
    sensitive << ( sum2_fu_400_p2 );

    SC_METHOD(thread_sum2_fu_400_p2);
    sensitive << ( tmp_37_reg_597 );
    sensitive << ( outrowidx_mid2_fu_394_p3 );

    SC_METHOD(thread_sum3_cast_fu_377_p1);
    sensitive << ( sum3_fu_373_p2 );

    SC_METHOD(thread_sum3_fu_373_p2);
    sensitive << ( tmp_37_reg_597 );
    sensitive << ( tmp1_mid2_reg_613 );

    SC_METHOD(thread_sum_cast_mid219_v_fu_357_p3);
    sensitive << ( sum_reg_551 );
    sensitive << ( exitcond_flatten_reg_560 );
    sensitive << ( tmp_35_reg_574 );

    SC_METHOD(thread_sum_cast_mid2_fu_368_p1);
    sensitive << ( sum_cast_mid2_v_fu_362_p3 );

    SC_METHOD(thread_sum_cast_mid2_v_fu_362_p3);
    sensitive << ( exitcond_mid3_reg_580 );
    sensitive << ( grp_fu_434_p3 );
    sensitive << ( sum_cast_mid219_v_fu_357_p3 );

    SC_METHOD(thread_tmp_30_fu_249_p0);
    sensitive << ( outcols );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tmp_30_fu_249_p1);
    sensitive << ( tmp_30_fu_249_p0 );

    SC_METHOD(thread_tmp_31_fu_234_p1);
    sensitive << ( innerdim );

    SC_METHOD(thread_tmp_32_fu_219_p1);
    sensitive << ( B_offset );

    SC_METHOD(thread_tmp_33_fu_257_p1);
    sensitive << ( ap_phi_mux_k_phi_fu_147_p4 );

    SC_METHOD(thread_tmp_34_fu_261_p1);
    sensitive << ( ap_phi_mux_i_phi_fu_169_p4 );

    SC_METHOD(thread_tmp_35_fu_289_p1);
    sensitive << ( k_s_fu_283_p2 );

    SC_METHOD(thread_tmp_36_fu_347_p1);
    sensitive << ( i_4_fu_342_p2 );

    SC_METHOD(thread_tmp_37_fu_327_p1);
    sensitive << ( j_mid2_fu_319_p3 );

    SC_METHOD(thread_tmp_7_fu_313_p2);
    sensitive << ( exitcond_flatten_fu_270_p2 );
    sensitive << ( exitcond_mid3_fu_298_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond3_fu_208_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond_flatten3_reg_556 );
    sensitive << ( ap_CS_fsm_pp0_stage5 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage3_subdone );
    sensitive << ( ap_block_pp0_stage5_subdone );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_block_pp0_stage2_subdone );
    sensitive << ( ap_block_pp0_stage4_subdone );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "k2c_matmul_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, C_address0, "(port)C_address0");
    sc_trace(mVcdFile, C_ce0, "(port)C_ce0");
    sc_trace(mVcdFile, C_we0, "(port)C_we0");
    sc_trace(mVcdFile, C_d0, "(port)C_d0");
    sc_trace(mVcdFile, C_q0, "(port)C_q0");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, A_address1, "(port)A_address1");
    sc_trace(mVcdFile, A_ce1, "(port)A_ce1");
    sc_trace(mVcdFile, A_q1, "(port)A_q1");
    sc_trace(mVcdFile, B_offset, "(port)B_offset");
    sc_trace(mVcdFile, outrows, "(port)outrows");
    sc_trace(mVcdFile, outcols, "(port)outcols");
    sc_trace(mVcdFile, innerdim, "(port)innerdim");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten3_reg_131, "indvar_flatten3_reg_131");
    sc_trace(mVcdFile, k_reg_143, "k_reg_143");
    sc_trace(mVcdFile, indvar_flatten_reg_154, "indvar_flatten_reg_154");
    sc_trace(mVcdFile, i_reg_165, "i_reg_165");
    sc_trace(mVcdFile, j_reg_176, "j_reg_176");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, grp_fu_197_p2, "grp_fu_197_p2");
    sc_trace(mVcdFile, tmp_reg_474, "tmp_reg_474");
    sc_trace(mVcdFile, a10_fu_213_p2, "a10_fu_213_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_32_fu_219_p1, "tmp_32_fu_219_p1");
    sc_trace(mVcdFile, tmp_32_reg_487, "tmp_32_reg_487");
    sc_trace(mVcdFile, exitcond3_fu_208_p2, "exitcond3_fu_208_p2");
    sc_trace(mVcdFile, grp_fu_228_p2, "grp_fu_228_p2");
    sc_trace(mVcdFile, bound_reg_502, "bound_reg_502");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_31_fu_234_p1, "tmp_31_fu_234_p1");
    sc_trace(mVcdFile, tmp_31_reg_508, "tmp_31_reg_508");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_30_fu_249_p1, "tmp_30_fu_249_p1");
    sc_trace(mVcdFile, tmp_30_reg_524, "tmp_30_reg_524");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_fu_243_p2, "grp_fu_243_p2");
    sc_trace(mVcdFile, bound5_reg_531, "bound5_reg_531");
    sc_trace(mVcdFile, exitcond_mid_fu_252_p2, "exitcond_mid_fu_252_p2");
    sc_trace(mVcdFile, exitcond_mid_reg_536, "exitcond_mid_reg_536");
    sc_trace(mVcdFile, tmp_33_fu_257_p1, "tmp_33_fu_257_p1");
    sc_trace(mVcdFile, tmp_33_reg_541, "tmp_33_reg_541");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter0, "ap_block_state7_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter1, "ap_block_state13_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, tmp_34_fu_261_p1, "tmp_34_fu_261_p1");
    sc_trace(mVcdFile, tmp_34_reg_546, "tmp_34_reg_546");
    sc_trace(mVcdFile, grp_fu_421_p3, "grp_fu_421_p3");
    sc_trace(mVcdFile, sum_reg_551, "sum_reg_551");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, exitcond_flatten3_fu_265_p2, "exitcond_flatten3_fu_265_p2");
    sc_trace(mVcdFile, exitcond_flatten3_reg_556, "exitcond_flatten3_reg_556");
    sc_trace(mVcdFile, exitcond_flatten3_reg_556_pp0_iter1_reg, "exitcond_flatten3_reg_556_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond_flatten_fu_270_p2, "exitcond_flatten_fu_270_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_560, "exitcond_flatten_reg_560");
    sc_trace(mVcdFile, i_mid_fu_275_p3, "i_mid_fu_275_p3");
    sc_trace(mVcdFile, i_mid_reg_568, "i_mid_reg_568");
    sc_trace(mVcdFile, tmp_35_fu_289_p1, "tmp_35_fu_289_p1");
    sc_trace(mVcdFile, tmp_35_reg_574, "tmp_35_reg_574");
    sc_trace(mVcdFile, exitcond_mid3_fu_298_p3, "exitcond_mid3_fu_298_p3");
    sc_trace(mVcdFile, exitcond_mid3_reg_580, "exitcond_mid3_reg_580");
    sc_trace(mVcdFile, k_mid2_fu_305_p3, "k_mid2_fu_305_p3");
    sc_trace(mVcdFile, k_mid2_reg_587, "k_mid2_reg_587");
    sc_trace(mVcdFile, j_mid2_fu_319_p3, "j_mid2_fu_319_p3");
    sc_trace(mVcdFile, j_mid2_reg_592, "j_mid2_reg_592");
    sc_trace(mVcdFile, tmp_37_fu_327_p1, "tmp_37_fu_327_p1");
    sc_trace(mVcdFile, tmp_37_reg_597, "tmp_37_reg_597");
    sc_trace(mVcdFile, indvar_flatten_op_fu_331_p2, "indvar_flatten_op_fu_331_p2");
    sc_trace(mVcdFile, indvar_flatten_op_reg_603, "indvar_flatten_op_reg_603");
    sc_trace(mVcdFile, k_cast_mid2_fu_337_p3, "k_cast_mid2_fu_337_p3");
    sc_trace(mVcdFile, k_cast_mid2_reg_608, "k_cast_mid2_reg_608");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage1_iter0, "ap_block_state8_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage1_iter1, "ap_block_state14_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, grp_fu_428_p3, "grp_fu_428_p3");
    sc_trace(mVcdFile, tmp1_mid2_reg_613, "tmp1_mid2_reg_613");
    sc_trace(mVcdFile, tmp_36_fu_347_p1, "tmp_36_fu_347_p1");
    sc_trace(mVcdFile, tmp_36_reg_618, "tmp_36_reg_618");
    sc_trace(mVcdFile, i_mid2_fu_351_p3, "i_mid2_fu_351_p3");
    sc_trace(mVcdFile, i_mid2_reg_624, "i_mid2_reg_624");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage2_iter0, "ap_block_state9_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage2_iter1, "ap_block_state15_pp0_stage2_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, outrowidx_fu_440_p2, "outrowidx_fu_440_p2");
    sc_trace(mVcdFile, outrowidx_reg_639, "outrowidx_reg_639");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage3, "ap_CS_fsm_pp0_stage3");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage3_iter0, "ap_block_state10_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage3_iter1, "ap_block_state16_pp0_stage3_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage3_11001, "ap_block_pp0_stage3_11001");
    sc_trace(mVcdFile, indvar_flatten_next3_fu_382_p2, "indvar_flatten_next3_fu_382_p2");
    sc_trace(mVcdFile, indvar_flatten_next3_reg_644, "indvar_flatten_next3_reg_644");
    sc_trace(mVcdFile, B_load_3_reg_649, "B_load_3_reg_649");
    sc_trace(mVcdFile, B_load_reg_654, "B_load_reg_654");
    sc_trace(mVcdFile, outrowidx_mid1_fu_444_p2, "outrowidx_mid1_fu_444_p2");
    sc_trace(mVcdFile, outrowidx_mid1_reg_659, "outrowidx_mid1_reg_659");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage4, "ap_CS_fsm_pp0_stage4");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage4_iter0, "ap_block_state11_pp0_stage4_iter0");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage4_iter1, "ap_block_state17_pp0_stage4_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage4_11001, "ap_block_pp0_stage4_11001");
    sc_trace(mVcdFile, C_addr_3_reg_664, "C_addr_3_reg_664");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage5, "ap_CS_fsm_pp0_stage5");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage5_iter0, "ap_block_state12_pp0_stage5_iter0");
    sc_trace(mVcdFile, ap_block_state18_pp0_stage5_iter1, "ap_block_state18_pp0_stage5_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage5_11001, "ap_block_pp0_stage5_11001");
    sc_trace(mVcdFile, j_1_fu_410_p2, "j_1_fu_410_p2");
    sc_trace(mVcdFile, j_1_reg_669, "j_1_reg_669");
    sc_trace(mVcdFile, indvar_flatten_next_fu_415_p3, "indvar_flatten_next_fu_415_p3");
    sc_trace(mVcdFile, indvar_flatten_next_reg_674, "indvar_flatten_next_reg_674");
    sc_trace(mVcdFile, grp_fu_193_p2, "grp_fu_193_p2");
    sc_trace(mVcdFile, tmp_3_reg_679, "tmp_3_reg_679");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage3_subdone, "ap_block_pp0_stage3_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state10, "ap_condition_pp0_exit_iter0_state10");
    sc_trace(mVcdFile, ap_block_pp0_stage5_subdone, "ap_block_pp0_stage5_subdone");
    sc_trace(mVcdFile, a_reg_120, "a_reg_120");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten3_phi_fu_135_p4, "ap_phi_mux_indvar_flatten3_phi_fu_135_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_k_phi_fu_147_p4, "ap_phi_mux_k_phi_fu_147_p4");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten_phi_fu_158_p4, "ap_phi_mux_indvar_flatten_phi_fu_158_p4");
    sc_trace(mVcdFile, ap_phi_mux_i_phi_fu_169_p4, "ap_phi_mux_i_phi_fu_169_p4");
    sc_trace(mVcdFile, ap_phi_mux_j_phi_fu_180_p4, "ap_phi_mux_j_phi_fu_180_p4");
    sc_trace(mVcdFile, a_cast_fu_203_p1, "a_cast_fu_203_p1");
    sc_trace(mVcdFile, sum_cast_mid2_fu_368_p1, "sum_cast_mid2_fu_368_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, sum3_cast_fu_377_p1, "sum3_cast_fu_377_p1");
    sc_trace(mVcdFile, sum2_cast_fu_405_p1, "sum2_cast_fu_405_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage5, "ap_block_pp0_stage5");
    sc_trace(mVcdFile, grp_fu_187_p2, "grp_fu_187_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, ap_block_pp0_stage4, "ap_block_pp0_stage4");
    sc_trace(mVcdFile, cast_fu_222_p0, "cast_fu_222_p0");
    sc_trace(mVcdFile, cast2_fu_225_p0, "cast2_fu_225_p0");
    sc_trace(mVcdFile, grp_fu_228_p0, "grp_fu_228_p0");
    sc_trace(mVcdFile, grp_fu_228_p1, "grp_fu_228_p1");
    sc_trace(mVcdFile, grp_fu_243_p0, "grp_fu_243_p0");
    sc_trace(mVcdFile, grp_fu_243_p1, "grp_fu_243_p1");
    sc_trace(mVcdFile, tmp_30_fu_249_p0, "tmp_30_fu_249_p0");
    sc_trace(mVcdFile, exitcond_mid_fu_252_p0, "exitcond_mid_fu_252_p0");
    sc_trace(mVcdFile, k_s_fu_283_p2, "k_s_fu_283_p2");
    sc_trace(mVcdFile, exitcond_fu_293_p1, "exitcond_fu_293_p1");
    sc_trace(mVcdFile, exitcond_fu_293_p2, "exitcond_fu_293_p2");
    sc_trace(mVcdFile, tmp_7_fu_313_p2, "tmp_7_fu_313_p2");
    sc_trace(mVcdFile, i_4_fu_342_p2, "i_4_fu_342_p2");
    sc_trace(mVcdFile, grp_fu_434_p3, "grp_fu_434_p3");
    sc_trace(mVcdFile, sum_cast_mid219_v_fu_357_p3, "sum_cast_mid219_v_fu_357_p3");
    sc_trace(mVcdFile, sum_cast_mid2_v_fu_362_p3, "sum_cast_mid2_v_fu_362_p3");
    sc_trace(mVcdFile, sum3_fu_373_p2, "sum3_fu_373_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage3, "ap_block_pp0_stage3");
    sc_trace(mVcdFile, outrowidx_mid_fu_388_p3, "outrowidx_mid_fu_388_p3");
    sc_trace(mVcdFile, outrowidx_mid2_fu_394_p3, "outrowidx_mid2_fu_394_p3");
    sc_trace(mVcdFile, sum2_fu_400_p2, "sum2_fu_400_p2");
    sc_trace(mVcdFile, grp_fu_421_p0, "grp_fu_421_p0");
    sc_trace(mVcdFile, grp_fu_421_p2, "grp_fu_421_p2");
    sc_trace(mVcdFile, grp_fu_428_p0, "grp_fu_428_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage4_subdone, "ap_block_pp0_stage4_subdone");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_228_p00, "grp_fu_228_p00");
    sc_trace(mVcdFile, grp_fu_228_p10, "grp_fu_228_p10");
    sc_trace(mVcdFile, grp_fu_243_p00, "grp_fu_243_p00");
    sc_trace(mVcdFile, grp_fu_243_p10, "grp_fu_243_p10");
#endif

    }
}

k2c_matmul::~k2c_matmul() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete WebModel_fadd_32ncud_U6;
    delete WebModel_fmul_32ndEe_U7;
    delete WebModel_mul_64s_bkb_U8;
    delete WebModel_mul_64nseOg_U9;
    delete WebModel_mul_128nfYi_U10;
    delete WebModel_mac_mulag8j_U11;
    delete WebModel_mac_mulag8j_U12;
    delete WebModel_mac_mulahbi_U13;
    delete WebModel_mul_mul_ibs_U14;
    delete WebModel_mul_mul_ibs_U15;
}

void k2c_matmul::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void k2c_matmul::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(exitcond3_fu_208_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        a_reg_120 = a10_fu_213_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        a_reg_120 = ap_const_lv15_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage3_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state10.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state10.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage5_subdone.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state10.read() ^ ap_const_logic_1);
        } else if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage5_subdone.read()) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1))) {
        i_reg_165 = i_mid2_reg_624.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_reg_165 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1))) {
        indvar_flatten3_reg_131 = indvar_flatten_next3_reg_644.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        indvar_flatten3_reg_131 = ap_const_lv192_lc_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1))) {
        indvar_flatten_reg_154 = indvar_flatten_next_reg_674.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        indvar_flatten_reg_154 = ap_const_lv128_lc_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1))) {
        j_reg_176 = j_1_reg_669.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_reg_176 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1))) {
        k_reg_143 = k_mid2_reg_587.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        k_reg_143 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0))) {
        B_load_3_reg_649 = A_q0.read();
        B_load_reg_654 = A_q1.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage5_11001.read(), ap_const_boolean_0))) {
        C_addr_3_reg_664 =  (sc_lv<15>) (sum2_cast_fu_405_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        bound5_reg_531 = grp_fu_243_p2.read();
        exitcond_mid_reg_536 = exitcond_mid_fu_252_p2.read();
        tmp_30_reg_524 = tmp_30_fu_249_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        bound_reg_502 = grp_fu_228_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten3_reg_556 = exitcond_flatten3_fu_265_p2.read();
        exitcond_flatten3_reg_556_pp0_iter1_reg = exitcond_flatten3_reg_556.read();
        tmp_33_reg_541 = tmp_33_fu_257_p1.read();
        tmp_34_reg_546 = tmp_34_fu_261_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten3_fu_265_p2.read(), ap_const_lv1_0))) {
        exitcond_flatten_reg_560 = exitcond_flatten_fu_270_p2.read();
        exitcond_mid3_reg_580 = exitcond_mid3_fu_298_p3.read();
        i_mid_reg_568 = i_mid_fu_275_p3.read();
        indvar_flatten_op_reg_603 = indvar_flatten_op_fu_331_p2.read();
        j_mid2_reg_592 = j_mid2_fu_319_p3.read();
        tmp_35_reg_574 = tmp_35_fu_289_p1.read();
        tmp_37_reg_597 = tmp_37_fu_327_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0))) {
        i_mid2_reg_624 = i_mid2_fu_351_p3.read();
        tmp1_mid2_reg_613 = grp_fu_428_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0))) {
        indvar_flatten_next3_reg_644 = indvar_flatten_next3_fu_382_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage5_11001.read(), ap_const_boolean_0))) {
        indvar_flatten_next_reg_674 = indvar_flatten_next_fu_415_p3.read();
        j_1_reg_669 = j_1_fu_410_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0))) {
        k_cast_mid2_reg_608 = k_cast_mid2_fu_337_p3.read();
        tmp_36_reg_618 = tmp_36_fu_347_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(exitcond_flatten3_fu_265_p2.read(), ap_const_lv1_0))) {
        k_mid2_reg_587 = k_mid2_fu_305_p3.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_mid3_reg_580.read()))) {
        outrowidx_mid1_reg_659 = outrowidx_mid1_fu_444_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_560.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_mid3_reg_580.read()))) {
        outrowidx_reg_639 = outrowidx_fu_440_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
        sum_reg_551 = grp_fu_421_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        tmp_31_reg_508 = tmp_31_fu_234_p1.read();
    }
    if ((esl_seteq<1,1,1>(exitcond3_fu_208_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        tmp_32_reg_487 = tmp_32_fu_219_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0))) {
        tmp_3_reg_679 = grp_fu_193_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        tmp_reg_474 = grp_fu_197_p2.read();
    }
}

void k2c_matmul::thread_A_address0() {
    A_address0 =  (sc_lv<15>) (sum_cast_mid2_fu_368_p1.read());
}

void k2c_matmul::thread_A_address1() {
    A_address1 =  (sc_lv<15>) (sum3_cast_fu_377_p1.read());
}

void k2c_matmul::thread_A_ce0() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void k2c_matmul::thread_A_ce1() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        A_ce1 = ap_const_logic_1;
    } else {
        A_ce1 = ap_const_logic_0;
    }
}

void k2c_matmul::thread_C_address0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage5.read(), ap_const_boolean_0)))) {
        C_address0 = C_addr_3_reg_664.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        C_address0 =  (sc_lv<15>) (a_cast_fu_203_p1.read());
    } else {
        C_address0 = "XXXXXXXXXXXXXXX";
    }
}

void k2c_matmul::thread_C_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage5_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1)))) {
        C_ce0 = ap_const_logic_1;
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void k2c_matmul::thread_C_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage5.read(), ap_const_boolean_0))) {
        C_d0 = grp_fu_187_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        C_d0 = ap_const_lv32_0;
    } else {
        C_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void k2c_matmul::thread_C_we0() {
    if (((esl_seteq<1,1,1>(exitcond3_fu_208_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage5_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(exitcond_flatten3_reg_556_pp0_iter1_reg.read(), ap_const_lv1_0)))) {
        C_we0 = ap_const_logic_1;
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void k2c_matmul::thread_a10_fu_213_p2() {
    a10_fu_213_p2 = (!a_reg_120.read().is_01() || !ap_const_lv15_1.is_01())? sc_lv<15>(): (sc_biguint<15>(a_reg_120.read()) + sc_biguint<15>(ap_const_lv15_1));
}

void k2c_matmul::thread_a_cast_fu_203_p1() {
    a_cast_fu_203_p1 = esl_zext<64,15>(a_reg_120.read());
}

void k2c_matmul::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[6];
}

void k2c_matmul::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[7];
}

void k2c_matmul::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[8];
}

void k2c_matmul::thread_ap_CS_fsm_pp0_stage3() {
    ap_CS_fsm_pp0_stage3 = ap_CS_fsm.read()[9];
}

void k2c_matmul::thread_ap_CS_fsm_pp0_stage4() {
    ap_CS_fsm_pp0_stage4 = ap_CS_fsm.read()[10];
}

void k2c_matmul::thread_ap_CS_fsm_pp0_stage5() {
    ap_CS_fsm_pp0_stage5 = ap_CS_fsm.read()[11];
}

void k2c_matmul::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void k2c_matmul::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[12];
}

void k2c_matmul::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void k2c_matmul::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void k2c_matmul::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void k2c_matmul::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void k2c_matmul::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void k2c_matmul::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage3() {
    ap_block_pp0_stage3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage3_11001() {
    ap_block_pp0_stage3_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage3_subdone() {
    ap_block_pp0_stage3_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage4() {
    ap_block_pp0_stage4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage4_11001() {
    ap_block_pp0_stage4_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage4_subdone() {
    ap_block_pp0_stage4_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage5() {
    ap_block_pp0_stage5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage5_11001() {
    ap_block_pp0_stage5_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_pp0_stage5_subdone() {
    ap_block_pp0_stage5_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state10_pp0_stage3_iter0() {
    ap_block_state10_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state11_pp0_stage4_iter0() {
    ap_block_state11_pp0_stage4_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state12_pp0_stage5_iter0() {
    ap_block_state12_pp0_stage5_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state13_pp0_stage0_iter1() {
    ap_block_state13_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state14_pp0_stage1_iter1() {
    ap_block_state14_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state15_pp0_stage2_iter1() {
    ap_block_state15_pp0_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state16_pp0_stage3_iter1() {
    ap_block_state16_pp0_stage3_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state17_pp0_stage4_iter1() {
    ap_block_state17_pp0_stage4_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state18_pp0_stage5_iter1() {
    ap_block_state18_pp0_stage5_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state7_pp0_stage0_iter0() {
    ap_block_state7_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state8_pp0_stage1_iter0() {
    ap_block_state8_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_block_state9_pp0_stage2_iter0() {
    ap_block_state9_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void k2c_matmul::thread_ap_condition_pp0_exit_iter0_state10() {
    if (esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state10 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state10 = ap_const_logic_0;
    }
}

void k2c_matmul::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void k2c_matmul::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void k2c_matmul::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void k2c_matmul::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void k2c_matmul::thread_ap_phi_mux_i_phi_fu_169_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_phi_fu_169_p4 = i_mid2_reg_624.read();
    } else {
        ap_phi_mux_i_phi_fu_169_p4 = i_reg_165.read();
    }
}

void k2c_matmul::thread_ap_phi_mux_indvar_flatten3_phi_fu_135_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten3_phi_fu_135_p4 = indvar_flatten_next3_reg_644.read();
    } else {
        ap_phi_mux_indvar_flatten3_phi_fu_135_p4 = indvar_flatten3_reg_131.read();
    }
}

void k2c_matmul::thread_ap_phi_mux_indvar_flatten_phi_fu_158_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten_phi_fu_158_p4 = indvar_flatten_next_reg_674.read();
    } else {
        ap_phi_mux_indvar_flatten_phi_fu_158_p4 = indvar_flatten_reg_154.read();
    }
}

void k2c_matmul::thread_ap_phi_mux_j_phi_fu_180_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_j_phi_fu_180_p4 = j_1_reg_669.read();
    } else {
        ap_phi_mux_j_phi_fu_180_p4 = j_reg_176.read();
    }
}

void k2c_matmul::thread_ap_phi_mux_k_phi_fu_147_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_k_phi_fu_147_p4 = k_mid2_reg_587.read();
    } else {
        ap_phi_mux_k_phi_fu_147_p4 = k_reg_143.read();
    }
}

void k2c_matmul::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void k2c_matmul::thread_cast2_fu_225_p0() {
    cast2_fu_225_p0 = outcols.read();
}

void k2c_matmul::thread_cast_fu_222_p0() {
    cast_fu_222_p0 = outrows.read();
}

void k2c_matmul::thread_exitcond3_fu_208_p2() {
    exitcond3_fu_208_p2 = (!a_cast_fu_203_p1.read().is_01() || !tmp_reg_474.read().is_01())? sc_lv<1>(): sc_lv<1>(a_cast_fu_203_p1.read() == tmp_reg_474.read());
}

void k2c_matmul::thread_exitcond_flatten3_fu_265_p2() {
    exitcond_flatten3_fu_265_p2 = (!ap_phi_mux_indvar_flatten3_phi_fu_135_p4.read().is_01() || !bound5_reg_531.read().is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten3_phi_fu_135_p4.read() == bound5_reg_531.read());
}

void k2c_matmul::thread_exitcond_flatten_fu_270_p2() {
    exitcond_flatten_fu_270_p2 = (!ap_phi_mux_indvar_flatten_phi_fu_158_p4.read().is_01() || !bound_reg_502.read().is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten_phi_fu_158_p4.read() == bound_reg_502.read());
}

void k2c_matmul::thread_exitcond_fu_293_p1() {
    exitcond_fu_293_p1 = outcols.read();
}

void k2c_matmul::thread_exitcond_fu_293_p2() {
    exitcond_fu_293_p2 = (!ap_phi_mux_j_phi_fu_180_p4.read().is_01() || !exitcond_fu_293_p1.read().is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_j_phi_fu_180_p4.read() == exitcond_fu_293_p1.read());
}

void k2c_matmul::thread_exitcond_mid3_fu_298_p3() {
    exitcond_mid3_fu_298_p3 = (!exitcond_flatten_fu_270_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_270_p2.read()[0].to_bool())? exitcond_mid_reg_536.read(): exitcond_fu_293_p2.read());
}

void k2c_matmul::thread_exitcond_mid_fu_252_p0() {
    exitcond_mid_fu_252_p0 = outcols.read();
}

void k2c_matmul::thread_exitcond_mid_fu_252_p2() {
    exitcond_mid_fu_252_p2 = (!exitcond_mid_fu_252_p0.read().is_01() || !ap_const_lv64_0.is_01())? sc_lv<1>(): sc_lv<1>(exitcond_mid_fu_252_p0.read() == ap_const_lv64_0);
}

void k2c_matmul::thread_grp_fu_228_p0() {
    grp_fu_228_p0 =  (sc_lv<64>) (grp_fu_228_p00.read());
}

void k2c_matmul::thread_grp_fu_228_p00() {
    grp_fu_228_p00 = esl_zext<128,64>(cast2_fu_225_p0.read());
}

void k2c_matmul::thread_grp_fu_228_p1() {
    grp_fu_228_p1 =  (sc_lv<64>) (grp_fu_228_p10.read());
}

void k2c_matmul::thread_grp_fu_228_p10() {
    grp_fu_228_p10 = esl_zext<128,64>(cast_fu_222_p0.read());
}

void k2c_matmul::thread_grp_fu_243_p0() {
    grp_fu_243_p0 =  (sc_lv<128>) (grp_fu_243_p00.read());
}

void k2c_matmul::thread_grp_fu_243_p00() {
    grp_fu_243_p00 = esl_zext<192,128>(bound_reg_502.read());
}

void k2c_matmul::thread_grp_fu_243_p1() {
    grp_fu_243_p1 =  (sc_lv<64>) (grp_fu_243_p10.read());
}

void k2c_matmul::thread_grp_fu_243_p10() {
    grp_fu_243_p10 = esl_zext<192,64>(innerdim.read());
}

void k2c_matmul::thread_grp_fu_421_p0() {
    grp_fu_421_p0 = ap_phi_mux_i_phi_fu_169_p4.read().range(16-1, 0);
}

void k2c_matmul::thread_grp_fu_421_p2() {
    grp_fu_421_p2 = ap_phi_mux_k_phi_fu_147_p4.read().range(16-1, 0);
}

void k2c_matmul::thread_grp_fu_428_p0() {
    grp_fu_428_p0 = (!exitcond_flatten_reg_560.read()[0].is_01())? sc_lv<16>(): ((exitcond_flatten_reg_560.read()[0].to_bool())? tmp_35_reg_574.read(): tmp_33_reg_541.read());
}

void k2c_matmul::thread_i_4_fu_342_p2() {
    i_4_fu_342_p2 = (!ap_const_lv64_1.is_01() || !i_mid_reg_568.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_1) + sc_biguint<64>(i_mid_reg_568.read()));
}

void k2c_matmul::thread_i_mid2_fu_351_p3() {
    i_mid2_fu_351_p3 = (!exitcond_mid3_reg_580.read()[0].is_01())? sc_lv<64>(): ((exitcond_mid3_reg_580.read()[0].to_bool())? i_4_fu_342_p2.read(): i_mid_reg_568.read());
}

void k2c_matmul::thread_i_mid_fu_275_p3() {
    i_mid_fu_275_p3 = (!exitcond_flatten_fu_270_p2.read()[0].is_01())? sc_lv<64>(): ((exitcond_flatten_fu_270_p2.read()[0].to_bool())? ap_const_lv64_0: ap_phi_mux_i_phi_fu_169_p4.read());
}

void k2c_matmul::thread_indvar_flatten_next3_fu_382_p2() {
    indvar_flatten_next3_fu_382_p2 = (!ap_const_lv192_lc_2.is_01() || !indvar_flatten3_reg_131.read().is_01())? sc_lv<192>(): (sc_biguint<192>(ap_const_lv192_lc_2) + sc_biguint<192>(indvar_flatten3_reg_131.read()));
}

void k2c_matmul::thread_indvar_flatten_next_fu_415_p3() {
    indvar_flatten_next_fu_415_p3 = (!exitcond_flatten_reg_560.read()[0].is_01())? sc_lv<128>(): ((exitcond_flatten_reg_560.read()[0].to_bool())? ap_const_lv128_lc_2: indvar_flatten_op_reg_603.read());
}

void k2c_matmul::thread_indvar_flatten_op_fu_331_p2() {
    indvar_flatten_op_fu_331_p2 = (!ap_const_lv128_lc_2.is_01() || !ap_phi_mux_indvar_flatten_phi_fu_158_p4.read().is_01())? sc_lv<128>(): (sc_biguint<128>(ap_const_lv128_lc_2) + sc_biguint<128>(ap_phi_mux_indvar_flatten_phi_fu_158_p4.read()));
}

void k2c_matmul::thread_j_1_fu_410_p2() {
    j_1_fu_410_p2 = (!ap_const_lv64_1.is_01() || !j_mid2_reg_592.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_1) + sc_biguint<64>(j_mid2_reg_592.read()));
}

void k2c_matmul::thread_j_mid2_fu_319_p3() {
    j_mid2_fu_319_p3 = (!tmp_7_fu_313_p2.read()[0].is_01())? sc_lv<64>(): ((tmp_7_fu_313_p2.read()[0].to_bool())? ap_const_lv64_0: ap_phi_mux_j_phi_fu_180_p4.read());
}

void k2c_matmul::thread_k_cast_mid2_fu_337_p3() {
    k_cast_mid2_fu_337_p3 = (!exitcond_flatten_reg_560.read()[0].is_01())? sc_lv<16>(): ((exitcond_flatten_reg_560.read()[0].to_bool())? tmp_35_reg_574.read(): tmp_33_reg_541.read());
}

void k2c_matmul::thread_k_mid2_fu_305_p3() {
    k_mid2_fu_305_p3 = (!exitcond_flatten_fu_270_p2.read()[0].is_01())? sc_lv<64>(): ((exitcond_flatten_fu_270_p2.read()[0].to_bool())? k_s_fu_283_p2.read(): ap_phi_mux_k_phi_fu_147_p4.read());
}

void k2c_matmul::thread_k_s_fu_283_p2() {
    k_s_fu_283_p2 = (!ap_const_lv64_1.is_01() || !ap_phi_mux_k_phi_fu_147_p4.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_1) + sc_biguint<64>(ap_phi_mux_k_phi_fu_147_p4.read()));
}

void k2c_matmul::thread_outrowidx_mid2_fu_394_p3() {
    outrowidx_mid2_fu_394_p3 = (!exitcond_mid3_reg_580.read()[0].is_01())? sc_lv<16>(): ((exitcond_mid3_reg_580.read()[0].to_bool())? outrowidx_mid1_reg_659.read(): outrowidx_mid_fu_388_p3.read());
}

void k2c_matmul::thread_outrowidx_mid_fu_388_p3() {
    outrowidx_mid_fu_388_p3 = (!exitcond_flatten_reg_560.read()[0].is_01())? sc_lv<16>(): ((exitcond_flatten_reg_560.read()[0].to_bool())? ap_const_lv16_0: outrowidx_reg_639.read());
}

void k2c_matmul::thread_sum2_cast_fu_405_p1() {
    sum2_cast_fu_405_p1 = esl_zext<64,16>(sum2_fu_400_p2.read());
}

void k2c_matmul::thread_sum2_fu_400_p2() {
    sum2_fu_400_p2 = (!tmp_37_reg_597.read().is_01() || !outrowidx_mid2_fu_394_p3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_37_reg_597.read()) + sc_biguint<16>(outrowidx_mid2_fu_394_p3.read()));
}

void k2c_matmul::thread_sum3_cast_fu_377_p1() {
    sum3_cast_fu_377_p1 = esl_zext<64,16>(sum3_fu_373_p2.read());
}

void k2c_matmul::thread_sum3_fu_373_p2() {
    sum3_fu_373_p2 = (!tmp1_mid2_reg_613.read().is_01() || !tmp_37_reg_597.read().is_01())? sc_lv<16>(): (sc_bigint<16>(tmp1_mid2_reg_613.read()) + sc_biguint<16>(tmp_37_reg_597.read()));
}

void k2c_matmul::thread_sum_cast_mid219_v_fu_357_p3() {
    sum_cast_mid219_v_fu_357_p3 = (!exitcond_flatten_reg_560.read()[0].is_01())? sc_lv<16>(): ((exitcond_flatten_reg_560.read()[0].to_bool())? tmp_35_reg_574.read(): sum_reg_551.read());
}

void k2c_matmul::thread_sum_cast_mid2_fu_368_p1() {
    sum_cast_mid2_fu_368_p1 = esl_zext<64,16>(sum_cast_mid2_v_fu_362_p3.read());
}

void k2c_matmul::thread_sum_cast_mid2_v_fu_362_p3() {
    sum_cast_mid2_v_fu_362_p3 = (!exitcond_mid3_reg_580.read()[0].is_01())? sc_lv<16>(): ((exitcond_mid3_reg_580.read()[0].to_bool())? grp_fu_434_p3.read(): sum_cast_mid219_v_fu_357_p3.read());
}

void k2c_matmul::thread_tmp_30_fu_249_p0() {
    tmp_30_fu_249_p0 = outcols.read();
}

void k2c_matmul::thread_tmp_30_fu_249_p1() {
    tmp_30_fu_249_p1 = tmp_30_fu_249_p0.read().range(16-1, 0);
}

void k2c_matmul::thread_tmp_31_fu_234_p1() {
    tmp_31_fu_234_p1 = innerdim.read().range(16-1, 0);
}

void k2c_matmul::thread_tmp_32_fu_219_p1() {
    tmp_32_fu_219_p1 = B_offset.read().range(16-1, 0);
}

void k2c_matmul::thread_tmp_33_fu_257_p1() {
    tmp_33_fu_257_p1 = ap_phi_mux_k_phi_fu_147_p4.read().range(16-1, 0);
}

void k2c_matmul::thread_tmp_34_fu_261_p1() {
    tmp_34_fu_261_p1 = ap_phi_mux_i_phi_fu_169_p4.read().range(16-1, 0);
}

void k2c_matmul::thread_tmp_35_fu_289_p1() {
    tmp_35_fu_289_p1 = k_s_fu_283_p2.read().range(16-1, 0);
}

void k2c_matmul::thread_tmp_36_fu_347_p1() {
    tmp_36_fu_347_p1 = i_4_fu_342_p2.read().range(16-1, 0);
}

void k2c_matmul::thread_tmp_37_fu_327_p1() {
    tmp_37_fu_327_p1 = j_mid2_fu_319_p3.read().range(16-1, 0);
}

void k2c_matmul::thread_tmp_7_fu_313_p2() {
    tmp_7_fu_313_p2 = (exitcond_mid3_fu_298_p3.read() | exitcond_flatten_fu_270_p2.read());
}

void k2c_matmul::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(exitcond3_fu_208_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 64 : 
            if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 128 : 
            if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage1_subdone.read())) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 256 : 
            if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage2_subdone.read())) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 512 : 
            if ((!(esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage3_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage3_subdone.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            } else if ((esl_seteq<1,1,1>(exitcond_flatten3_reg_556.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage3_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        case 1024 : 
            if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage4_subdone.read())) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            }
            break;
        case 2048 : 
            if ((!(esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage5_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage5_subdone.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage5_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<13>) ("XXXXXXXXXXXXX");
            break;
    }
}

}

