// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _k2c_dense_2_HH_
#define _k2c_dense_2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "k2c_dot.h"
#include "k2c_affine_matmul.h"
#include "k2c_relu_func.h"
#include "WebModel_fadd_32ncud.h"
#include "WebModel_mul_64s_bkb.h"

namespace ap_rtl {

struct k2c_dense_2 : public sc_module {
    // Port declarations 32
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<15> > output_array_address0;
    sc_out< sc_logic > output_array_ce0;
    sc_out< sc_logic > output_array_we0;
    sc_out< sc_lv<32> > output_array_d0;
    sc_in< sc_lv<32> > output_array_q0;
    sc_out< sc_lv<15> > output_array_address1;
    sc_out< sc_logic > output_array_ce1;
    sc_out< sc_logic > output_array_we1;
    sc_out< sc_lv<32> > output_array_d1;
    sc_out< sc_lv<15> > input_array_address0;
    sc_out< sc_logic > input_array_ce0;
    sc_in< sc_lv<32> > input_array_q0;
    sc_in< sc_lv<64> > input_ndim_read;
    sc_in< sc_lv<64> > input_numel_read;
    sc_out< sc_lv<3> > input_shape_address0;
    sc_out< sc_logic > input_shape_ce0;
    sc_in< sc_lv<64> > input_shape_q0;
    sc_out< sc_lv<15> > kernel_array_address0;
    sc_out< sc_logic > kernel_array_ce0;
    sc_in< sc_lv<32> > kernel_array_q0;
    sc_out< sc_lv<3> > kernel_shape_address0;
    sc_out< sc_logic > kernel_shape_ce0;
    sc_in< sc_lv<64> > kernel_shape_q0;
    sc_out< sc_lv<15> > bias_array_address0;
    sc_out< sc_logic > bias_array_ce0;
    sc_in< sc_lv<32> > bias_array_q0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    k2c_dense_2(sc_module_name name);
    SC_HAS_PROCESS(k2c_dense_2);

    ~k2c_dense_2();

    sc_trace_file* mVcdFile;

    k2c_dot* grp_k2c_dot_fu_176;
    k2c_affine_matmul* grp_k2c_affine_matmul_fu_197;
    k2c_relu_func* grp_k2c_relu_func_fu_213;
    WebModel_fadd_32ncud<1,5,32,32,32>* WebModel_fadd_32ncud_U67;
    WebModel_mul_64s_bkb<1,2,64,64,64>* WebModel_mul_64s_bkb_U68;
    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<7> > indvar_flatten_reg_143;
    sc_signal< sc_lv<7> > i_i_reg_154;
    sc_signal< sc_lv<7> > j_i_reg_165;
    sc_signal< sc_lv<1> > tmp_fu_225_p2;
    sc_signal< sc_lv<1> > tmp_reg_337;
    sc_signal< sc_lv<64> > tmp_1_fu_231_p2;
    sc_signal< sc_lv<64> > tmp_1_reg_341;
    sc_signal< sc_lv<1> > icmp_fu_248_p2;
    sc_signal< sc_lv<1> > icmp_reg_346;
    sc_signal< sc_lv<1> > exitcond_flatten_fu_254_p2;
    sc_signal< sc_lv<1> > exitcond_flatten_reg_361;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter4;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter5;
    sc_signal< bool > ap_block_state9_pp0_stage0_iter6;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter7;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<1> > exitcond_flatten_reg_361_pp0_iter1_reg;
    sc_signal< sc_lv<1> > exitcond_flatten_reg_361_pp0_iter2_reg;
    sc_signal< sc_lv<1> > exitcond_flatten_reg_361_pp0_iter3_reg;
    sc_signal< sc_lv<1> > exitcond_flatten_reg_361_pp0_iter4_reg;
    sc_signal< sc_lv<1> > exitcond_flatten_reg_361_pp0_iter5_reg;
    sc_signal< sc_lv<1> > exitcond_flatten_reg_361_pp0_iter6_reg;
    sc_signal< sc_lv<7> > indvar_flatten_next_fu_260_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<7> > i_i_mid2_fu_286_p3;
    sc_signal< sc_lv<7> > i_i_mid2_reg_370;
    sc_signal< sc_lv<15> > output_array_addr_reg_380;
    sc_signal< sc_lv<15> > output_array_addr_reg_380_pp0_iter1_reg;
    sc_signal< sc_lv<15> > output_array_addr_reg_380_pp0_iter2_reg;
    sc_signal< sc_lv<15> > output_array_addr_reg_380_pp0_iter3_reg;
    sc_signal< sc_lv<15> > output_array_addr_reg_380_pp0_iter4_reg;
    sc_signal< sc_lv<15> > output_array_addr_reg_380_pp0_iter5_reg;
    sc_signal< sc_lv<15> > output_array_addr_reg_380_pp0_iter6_reg;
    sc_signal< sc_lv<7> > j_fu_310_p2;
    sc_signal< sc_lv<32> > bias_array_load_reg_391;
    sc_signal< sc_lv<32> > output_array_load_reg_396;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<32> > grp_fu_221_p2;
    sc_signal< sc_lv<32> > tmp_4_i_reg_401;
    sc_signal< sc_lv<64> > outrows1_fu_316_p3;
    sc_signal< sc_lv<64> > outrows1_reg_406;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<64> > outcols_reg_412;
    sc_signal< sc_lv<64> > innerdim_reg_423;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<64> > grp_fu_323_p2;
    sc_signal< sc_lv<64> > outsize_reg_428;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_197_ap_idle;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_197_ap_ready;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_197_ap_done;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > grp_k2c_dot_fu_176_ap_idle;
    sc_signal< sc_logic > grp_k2c_dot_fu_176_ap_ready;
    sc_signal< sc_logic > grp_k2c_dot_fu_176_ap_done;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter4;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter5;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter6;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter7;
    sc_signal< sc_logic > grp_k2c_dot_fu_176_ap_start;
    sc_signal< sc_lv<15> > grp_k2c_dot_fu_176_C_array_address0;
    sc_signal< sc_logic > grp_k2c_dot_fu_176_C_array_ce0;
    sc_signal< sc_logic > grp_k2c_dot_fu_176_C_array_we0;
    sc_signal< sc_lv<32> > grp_k2c_dot_fu_176_C_array_d0;
    sc_signal< sc_lv<15> > grp_k2c_dot_fu_176_A_array_address0;
    sc_signal< sc_logic > grp_k2c_dot_fu_176_A_array_ce0;
    sc_signal< sc_lv<3> > grp_k2c_dot_fu_176_A_shape_address0;
    sc_signal< sc_logic > grp_k2c_dot_fu_176_A_shape_ce0;
    sc_signal< sc_lv<15> > grp_k2c_dot_fu_176_B_array_address0;
    sc_signal< sc_logic > grp_k2c_dot_fu_176_B_array_ce0;
    sc_signal< sc_lv<3> > grp_k2c_dot_fu_176_B_shape_address0;
    sc_signal< sc_logic > grp_k2c_dot_fu_176_B_shape_ce0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_197_ap_start;
    sc_signal< sc_lv<15> > grp_k2c_affine_matmul_fu_197_C_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_197_C_ce0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_197_C_we0;
    sc_signal< sc_lv<32> > grp_k2c_affine_matmul_fu_197_C_d0;
    sc_signal< sc_lv<15> > grp_k2c_affine_matmul_fu_197_A_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_197_A_ce0;
    sc_signal< sc_lv<15> > grp_k2c_affine_matmul_fu_197_B_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_197_B_ce0;
    sc_signal< sc_lv<15> > grp_k2c_affine_matmul_fu_197_d_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_197_d_ce0;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_213_ap_start;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_213_ap_done;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_213_ap_idle;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_213_ap_ready;
    sc_signal< sc_lv<15> > grp_k2c_relu_func_fu_213_x_address0;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_213_x_ce0;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_213_x_we0;
    sc_signal< sc_lv<32> > grp_k2c_relu_func_fu_213_x_d0;
    sc_signal< sc_lv<64> > grp_k2c_relu_func_fu_213_size;
    sc_signal< sc_lv<7> > ap_phi_mux_i_i_phi_fu_158_p4;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_logic > grp_k2c_dot_fu_176_ap_start_reg;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_197_ap_start_reg;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_213_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<64> > j_i_cast1_fu_294_p1;
    sc_signal< sc_lv<64> > tmp_i_cast_fu_305_p1;
    sc_signal< sc_lv<63> > tmp_58_fu_238_p4;
    sc_signal< sc_lv<1> > exitcond_i4_fu_266_p2;
    sc_signal< sc_lv<7> > i2_fu_280_p2;
    sc_signal< sc_lv<7> > j_i_mid2_fu_272_p3;
    sc_signal< sc_lv<7> > tmp_i_fu_299_p2;
    sc_signal< sc_logic > grp_fu_323_ce;
    sc_signal< bool > ap_block_state17_on_subcall_done;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_fsm_state1;
    static const sc_lv<10> ap_ST_fsm_state2;
    static const sc_lv<10> ap_ST_fsm_pp0_stage0;
    static const sc_lv<10> ap_ST_fsm_state11;
    static const sc_lv<10> ap_ST_fsm_state12;
    static const sc_lv<10> ap_ST_fsm_state13;
    static const sc_lv<10> ap_ST_fsm_state14;
    static const sc_lv<10> ap_ST_fsm_state15;
    static const sc_lv<10> ap_ST_fsm_state16;
    static const sc_lv<10> ap_ST_fsm_state17;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<64> ap_const_lv64_40;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_FFFFFFFFFFFFFFFF;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<63> ap_const_lv63_0;
    static const sc_lv<7> ap_const_lv7_40;
    static const sc_lv<7> ap_const_lv7_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state10_pp0_stage0_iter7();
    void thread_ap_block_state17_on_subcall_done();
    void thread_ap_block_state3_pp0_stage0_iter0();
    void thread_ap_block_state4_pp0_stage0_iter1();
    void thread_ap_block_state5_pp0_stage0_iter2();
    void thread_ap_block_state6_pp0_stage0_iter3();
    void thread_ap_block_state7_pp0_stage0_iter4();
    void thread_ap_block_state8_pp0_stage0_iter5();
    void thread_ap_block_state9_pp0_stage0_iter6();
    void thread_ap_condition_pp0_exit_iter0_state3();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_i_i_phi_fu_158_p4();
    void thread_ap_ready();
    void thread_bias_array_address0();
    void thread_bias_array_ce0();
    void thread_exitcond_flatten_fu_254_p2();
    void thread_exitcond_i4_fu_266_p2();
    void thread_grp_fu_323_ce();
    void thread_grp_k2c_affine_matmul_fu_197_ap_start();
    void thread_grp_k2c_dot_fu_176_ap_start();
    void thread_grp_k2c_relu_func_fu_213_ap_start();
    void thread_grp_k2c_relu_func_fu_213_size();
    void thread_i2_fu_280_p2();
    void thread_i_i_mid2_fu_286_p3();
    void thread_icmp_fu_248_p2();
    void thread_indvar_flatten_next_fu_260_p2();
    void thread_input_array_address0();
    void thread_input_array_ce0();
    void thread_input_shape_address0();
    void thread_input_shape_ce0();
    void thread_j_fu_310_p2();
    void thread_j_i_cast1_fu_294_p1();
    void thread_j_i_mid2_fu_272_p3();
    void thread_kernel_array_address0();
    void thread_kernel_array_ce0();
    void thread_kernel_shape_address0();
    void thread_kernel_shape_ce0();
    void thread_output_array_address0();
    void thread_output_array_address1();
    void thread_output_array_ce0();
    void thread_output_array_ce1();
    void thread_output_array_d0();
    void thread_output_array_d1();
    void thread_output_array_we0();
    void thread_output_array_we1();
    void thread_outrows1_fu_316_p3();
    void thread_tmp_1_fu_231_p2();
    void thread_tmp_58_fu_238_p4();
    void thread_tmp_fu_225_p2();
    void thread_tmp_i_cast_fu_305_p1();
    void thread_tmp_i_fu_299_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
