// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _k2c_dense_1_HH_
#define _k2c_dense_1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "k2c_dot_1.h"
#include "k2c_affine_matmul.h"
#include "k2c_relu_func.h"
#include "WebModel_fadd_32ncud.h"
#include "WebModel_mul_64s_bkb.h"

namespace ap_rtl {

struct k2c_dense_1 : public sc_module {
    // Port declarations 32
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<15> > output_array_address0;
    sc_out< sc_logic > output_array_ce0;
    sc_out< sc_logic > output_array_we0;
    sc_out< sc_lv<32> > output_array_d0;
    sc_in< sc_lv<32> > output_array_q0;
    sc_in< sc_lv<64> > output_numel_read;
    sc_out< sc_lv<15> > input_array_address0;
    sc_out< sc_logic > input_array_ce0;
    sc_in< sc_lv<32> > input_array_q0;
    sc_in< sc_lv<64> > input_ndim_read;
    sc_in< sc_lv<64> > input_numel_read;
    sc_out< sc_lv<3> > input_shape_address0;
    sc_out< sc_logic > input_shape_ce0;
    sc_in< sc_lv<64> > input_shape_q0;
    sc_out< sc_lv<15> > kernel_array_address0;
    sc_out< sc_logic > kernel_array_ce0;
    sc_in< sc_lv<32> > kernel_array_q0;
    sc_in< sc_lv<64> > kernel_ndim_read;
    sc_in< sc_lv<64> > kernel_numel_read;
    sc_out< sc_lv<3> > kernel_shape_address0;
    sc_out< sc_logic > kernel_shape_ce0;
    sc_in< sc_lv<64> > kernel_shape_q0;
    sc_out< sc_lv<15> > bias_array_address0;
    sc_out< sc_logic > bias_array_ce0;
    sc_in< sc_lv<32> > bias_array_q0;
    sc_in< sc_lv<64> > bias_numel_read;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    k2c_dense_1(sc_module_name name);
    SC_HAS_PROCESS(k2c_dense_1);

    ~k2c_dense_1();

    sc_trace_file* mVcdFile;

    k2c_dot_1* grp_k2c_dot_1_fu_186;
    k2c_affine_matmul* grp_k2c_affine_matmul_fu_211;
    k2c_relu_func* grp_k2c_relu_func_fu_227;
    WebModel_fadd_32ncud<1,5,32,32,32>* WebModel_fadd_32ncud_U112;
    WebModel_mul_64s_bkb<1,2,64,64,64>* WebModel_mul_64s_bkb_U113;
    sc_signal< sc_lv<16> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<64> > j_i_reg_174;
    sc_signal< sc_lv<1> > tmp_fu_240_p2;
    sc_signal< sc_lv<1> > tmp_reg_351;
    sc_signal< sc_lv<64> > tmp_2_fu_246_p2;
    sc_signal< sc_lv<64> > tmp_2_reg_355;
    sc_signal< sc_lv<1> > icmp_fu_263_p2;
    sc_signal< sc_lv<1> > icmp_reg_360;
    sc_signal< sc_lv<1> > tmp_i_fu_269_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<16> > tmp_60_fu_274_p1;
    sc_signal< sc_lv<16> > tmp_60_reg_379;
    sc_signal< sc_lv<1> > exitcond_i_fu_278_p2;
    sc_signal< sc_lv<1> > exitcond_i_reg_384;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<64> > j_fu_283_p2;
    sc_signal< sc_lv<64> > j_reg_388;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<15> > output_array_addr_reg_398;
    sc_signal< sc_lv<32> > bias_array_load_reg_403;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage1;
    sc_signal< bool > ap_block_state5_pp0_stage1_iter0;
    sc_signal< bool > ap_block_pp0_stage1_11001;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage2;
    sc_signal< bool > ap_block_state6_pp0_stage2_iter0;
    sc_signal< bool > ap_block_pp0_stage2_11001;
    sc_signal< sc_lv<64> > i_fu_303_p2;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<64> > outrows1_fu_308_p3;
    sc_signal< sc_lv<64> > outrows1_reg_418;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<64> > outcols_reg_424;
    sc_signal< sc_lv<64> > innerdim_reg_435;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<64> > grp_fu_315_p2;
    sc_signal< sc_lv<64> > outsize_reg_440;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_211_ap_idle;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_211_ap_ready;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_211_ap_done;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state4;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_state9_pp0_stage5_iter0;
    sc_signal< bool > ap_block_pp0_stage5_subdone;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage5;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_186_ap_start;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_186_ap_done;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_186_ap_idle;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_186_ap_ready;
    sc_signal< sc_lv<15> > grp_k2c_dot_1_fu_186_C_array_address0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_186_C_array_ce0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_186_C_array_we0;
    sc_signal< sc_lv<32> > grp_k2c_dot_1_fu_186_C_array_d0;
    sc_signal< sc_lv<15> > grp_k2c_dot_1_fu_186_A_array_address0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_186_A_array_ce0;
    sc_signal< sc_lv<3> > grp_k2c_dot_1_fu_186_A_shape_address0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_186_A_shape_ce0;
    sc_signal< sc_lv<15> > grp_k2c_dot_1_fu_186_B_array_address0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_186_B_array_ce0;
    sc_signal< sc_lv<3> > grp_k2c_dot_1_fu_186_B_shape_address0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_186_B_shape_ce0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_211_ap_start;
    sc_signal< sc_lv<15> > grp_k2c_affine_matmul_fu_211_C_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_211_C_ce0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_211_C_we0;
    sc_signal< sc_lv<32> > grp_k2c_affine_matmul_fu_211_C_d0;
    sc_signal< sc_lv<15> > grp_k2c_affine_matmul_fu_211_A_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_211_A_ce0;
    sc_signal< sc_lv<15> > grp_k2c_affine_matmul_fu_211_B_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_211_B_ce0;
    sc_signal< sc_lv<15> > grp_k2c_affine_matmul_fu_211_d_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_211_d_ce0;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_227_ap_start;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_227_ap_done;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_227_ap_idle;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_227_ap_ready;
    sc_signal< sc_lv<15> > grp_k2c_relu_func_fu_227_x_address0;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_227_x_ce0;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_227_x_we0;
    sc_signal< sc_lv<32> > grp_k2c_relu_func_fu_227_x_d0;
    sc_signal< sc_lv<64> > grp_k2c_relu_func_fu_227_size;
    sc_signal< sc_lv<64> > i_i_reg_162;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<64> > ap_phi_mux_j_i_phi_fu_178_p4;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_186_ap_start_reg;
    sc_signal< sc_logic > grp_k2c_affine_matmul_fu_211_ap_start_reg;
    sc_signal< sc_logic > grp_k2c_relu_func_fu_227_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<64> > tmp_i_cast_fu_298_p1;
    sc_signal< bool > ap_block_pp0_stage1;
    sc_signal< sc_lv<32> > grp_fu_234_p2;
    sc_signal< bool > ap_block_pp0_stage2;
    sc_signal< sc_lv<63> > tmp_59_fu_253_p4;
    sc_signal< sc_lv<16> > tmp_61_fu_289_p1;
    sc_signal< sc_lv<16> > tmp_i_26_fu_293_p2;
    sc_signal< sc_logic > grp_fu_315_ce;
    sc_signal< bool > ap_block_state17_on_subcall_done;
    sc_signal< sc_lv<16> > ap_NS_fsm;
    sc_signal< bool > ap_block_pp0_stage1_subdone;
    sc_signal< bool > ap_block_pp0_stage2_subdone;
    sc_signal< bool > ap_block_state7_pp0_stage3_iter0;
    sc_signal< bool > ap_block_pp0_stage3_subdone;
    sc_signal< bool > ap_block_state8_pp0_stage4_iter0;
    sc_signal< bool > ap_block_pp0_stage4_subdone;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<16> ap_ST_fsm_state1;
    static const sc_lv<16> ap_ST_fsm_state2;
    static const sc_lv<16> ap_ST_fsm_state3;
    static const sc_lv<16> ap_ST_fsm_pp0_stage0;
    static const sc_lv<16> ap_ST_fsm_pp0_stage1;
    static const sc_lv<16> ap_ST_fsm_pp0_stage2;
    static const sc_lv<16> ap_ST_fsm_pp0_stage3;
    static const sc_lv<16> ap_ST_fsm_pp0_stage4;
    static const sc_lv<16> ap_ST_fsm_pp0_stage5;
    static const sc_lv<16> ap_ST_fsm_state11;
    static const sc_lv<16> ap_ST_fsm_state12;
    static const sc_lv<16> ap_ST_fsm_state13;
    static const sc_lv<16> ap_ST_fsm_state14;
    static const sc_lv<16> ap_ST_fsm_state15;
    static const sc_lv<16> ap_ST_fsm_state16;
    static const sc_lv<16> ap_ST_fsm_state17;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_FFFFFFFFFFFFFFFF;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<63> ap_const_lv63_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_CS_fsm_pp0_stage2();
    void thread_ap_CS_fsm_pp0_stage5();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_pp0_stage1();
    void thread_ap_block_pp0_stage1_11001();
    void thread_ap_block_pp0_stage1_subdone();
    void thread_ap_block_pp0_stage2();
    void thread_ap_block_pp0_stage2_11001();
    void thread_ap_block_pp0_stage2_subdone();
    void thread_ap_block_pp0_stage3_subdone();
    void thread_ap_block_pp0_stage4_subdone();
    void thread_ap_block_pp0_stage5_subdone();
    void thread_ap_block_state10_pp0_stage0_iter1();
    void thread_ap_block_state17_on_subcall_done();
    void thread_ap_block_state4_pp0_stage0_iter0();
    void thread_ap_block_state5_pp0_stage1_iter0();
    void thread_ap_block_state6_pp0_stage2_iter0();
    void thread_ap_block_state7_pp0_stage3_iter0();
    void thread_ap_block_state8_pp0_stage4_iter0();
    void thread_ap_block_state9_pp0_stage5_iter0();
    void thread_ap_condition_pp0_exit_iter0_state4();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_j_i_phi_fu_178_p4();
    void thread_ap_ready();
    void thread_bias_array_address0();
    void thread_bias_array_ce0();
    void thread_exitcond_i_fu_278_p2();
    void thread_grp_fu_315_ce();
    void thread_grp_k2c_affine_matmul_fu_211_ap_start();
    void thread_grp_k2c_dot_1_fu_186_ap_start();
    void thread_grp_k2c_relu_func_fu_227_ap_start();
    void thread_grp_k2c_relu_func_fu_227_size();
    void thread_i_fu_303_p2();
    void thread_icmp_fu_263_p2();
    void thread_input_array_address0();
    void thread_input_array_ce0();
    void thread_input_shape_address0();
    void thread_input_shape_ce0();
    void thread_j_fu_283_p2();
    void thread_kernel_array_address0();
    void thread_kernel_array_ce0();
    void thread_kernel_shape_address0();
    void thread_kernel_shape_ce0();
    void thread_output_array_address0();
    void thread_output_array_ce0();
    void thread_output_array_d0();
    void thread_output_array_we0();
    void thread_outrows1_fu_308_p3();
    void thread_tmp_2_fu_246_p2();
    void thread_tmp_59_fu_253_p4();
    void thread_tmp_60_fu_274_p1();
    void thread_tmp_61_fu_289_p1();
    void thread_tmp_fu_240_p2();
    void thread_tmp_i_26_fu_293_p2();
    void thread_tmp_i_cast_fu_298_p1();
    void thread_tmp_i_fu_269_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
