// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __WebModel_dense_70Mgi_H__
#define __WebModel_dense_70Mgi_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct WebModel_dense_70Mgi_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 8;
  static const unsigned AddressWidth = 3;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(WebModel_dense_70Mgi_ram) {
        ram[0] = "0b00111100011001100101000011111011";
        ram[1] = "0b00111110001110010000110111000101";
        ram[2] = "0b10111100100011010001100100000111";
        ram[3] = "0b10111101100110111111011100110001";
        ram[4] = "0b10111100111110011001000010100101";
        ram[5] = "0b00111110001010100001000001111000";
        ram[6] = "0b10111110000000010110100101111111";
        ram[7] = "0b10111110110000010001011110000010";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(WebModel_dense_70Mgi) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 8;
static const unsigned AddressWidth = 3;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


WebModel_dense_70Mgi_ram* meminst;


SC_CTOR(WebModel_dense_70Mgi) {
meminst = new WebModel_dense_70Mgi_ram("WebModel_dense_70Mgi_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~WebModel_dense_70Mgi() {
    delete meminst;
}


};//endmodule
#endif
